<?php
return array(
    'name' => 'Course',
    'description' => 'Course schema markup for educational content',
    'fields' => array(
        array(
            'key' => 'name',
            'label' => 'Course Name',
            'type' => 'text',
            'placeholder' => 'Digital Marketing Masterclass',
            'required' => true,
            'help' => 'The name of the course',
        ),
        array(
            'key' => 'description',
            'label' => 'Description',
            'type' => 'textarea',
            'placeholder' => 'Enter course description',
            'required' => true,
            'help' => 'A description of the course',
        ),
        array(
            'key' => 'provider',
            'label' => 'Provider Name',
            'type' => 'text',
            'placeholder' => 'Digital Academy 360',
            'required' => true,
            'help' => 'The organization providing the course',
        ),
        array(
            'key' => 'providerUrl',
            'label' => 'Provider URL',
            'type' => 'text',
            'placeholder' => 'https://example.com',
            'required' => false,
            'help' => 'URL of the course provider',
        ),
        array(
            'key' => 'courseMode',
            'label' => 'Course Mode',
            'type' => 'select',
            'options' => array(
                'online' => 'Online',
                'onsite' => 'On-site',
                'blended' => 'Blended',
            ),
            'required' => false,
            'help' => 'The mode of the course',
        ),
        array(
            'key' => 'duration',
            'label' => 'Duration',
            'type' => 'text',
            'placeholder' => 'P3M',
            'required' => false,
            'help' => 'Course duration in ISO 8601 format (e.g., P3M for 3 months)',
        ),
        array(
            'key' => 'price',
            'label' => 'Price',
            'type' => 'text',
            'placeholder' => '299',
            'required' => false,
            'help' => 'Price of the course',
        ),
        array(
            'key' => 'currency',
            'label' => 'Currency',
            'type' => 'text',
            'placeholder' => 'USD',
            'required' => false,
            'help' => 'Currency code (USD, EUR, INR, etc.)',
        ),
    ),
);
