<?php
return array(
    'name' => 'Job Posting',
    'description' => 'Job posting schema markup for job listings',
    'fields' => array(
        array(
            'key' => 'title',
            'label' => 'Job Title',
            'type' => 'text',
            'placeholder' => 'Digital Marketing Specialist',
            'required' => true,
            'help' => 'The title of the job position',
        ),
        array(
            'key' => 'description',
            'label' => 'Description',
            'type' => 'textarea',
            'placeholder' => 'Enter job description',
            'required' => true,
            'help' => 'A description of the job',
        ),
        array(
            'key' => 'hiringOrganization',
            'label' => 'Company Name',
            'type' => 'text',
            'placeholder' => 'Digital Academy 360',
            'required' => true,
            'help' => 'Name of the hiring organization',
        ),
        array(
            'key' => 'location',
            'label' => 'Job Location',
            'type' => 'text',
            'placeholder' => 'Bangalore, Karnataka, India',
            'required' => true,
            'help' => 'Location where the job is available',
        ),
        array(
            'key' => 'datePosted',
            'label' => 'Date Posted',
            'type' => 'date',
            'placeholder' => '2024-01-01',
            'required' => true,
            'help' => 'The date the job was posted',
        ),
        array(
            'key' => 'employmentType',
            'label' => 'Employment Type',
            'type' => 'select',
            'options' => array(
                'FULL_TIME' => 'Full Time',
                'PART_TIME' => 'Part Time',
                'CONTRACT' => 'Contract',
                'TEMPORARY' => 'Temporary',
                'INTERN' => 'Internship',
            ),
            'required' => false,
            'help' => 'Type of employment',
        ),
        array(
            'key' => 'baseSalary',
            'label' => 'Salary',
            'type' => 'text',
            'placeholder' => '50000',
            'required' => false,
            'help' => 'Base salary amount',
        ),
        array(
            'key' => 'currency',
            'label' => 'Currency',
            'type' => 'text',
            'placeholder' => 'INR',
            'required' => false,
            'help' => 'Currency code (USD, EUR, INR, etc.)',
        ),
    ),
);
