<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

return array(
    array(
        'key' => '@type',
        'label' => 'Type',
        'type' => 'hidden',
        'default' => 'LocalBusiness',
        'required' => true,
    ),
    array(
        'key' => 'name',
        'label' => 'Business Name',
        'type' => 'text',
        'placeholder' => 'Your Business Name',
        'required' => true,
        'help' => 'The name of your business',
    ),
    array(
        'key' => 'description',
        'label' => 'Description',
        'type' => 'textarea',
        'placeholder' => 'Describe your business',
        'required' => false,
    ),
    array(
        'key' => 'image',
        'label' => 'Business Image URL',
        'type' => 'url',
        'placeholder' => 'https://example.com/business.jpg',
        'required' => false,
    ),
    array(
        'key' => 'telephone',
        'label' => 'Phone Number',
        'type' => 'text',
        'placeholder' => '+1-555-555-5555',
        'required' => false,
    ),
    array(
        'key' => 'address',
        'label' => 'Address',
        'type' => 'group',
        'required' => true,
        'fields' => array(
            array(
                'key' => 'streetAddress',
                'label' => 'Street Address',
                'type' => 'text',
                'placeholder' => '123 Main Street',
                'required' => true,
            ),
            array(
                'key' => 'addressLocality',
                'label' => 'City',
                'type' => 'text',
                'placeholder' => 'San Francisco',
                'required' => true,
            ),
            array(
                'key' => 'addressRegion',
                'label' => 'State/Region',
                'type' => 'text',
                'placeholder' => 'CA',
                'required' => true,
            ),
            array(
                'key' => 'postalCode',
                'label' => 'Postal Code',
                'type' => 'text',
                'placeholder' => '94103',
                'required' => true,
            ),
            array(
                'key' => 'addressCountry',
                'label' => 'Country',
                'type' => 'text',
                'placeholder' => 'US',
                'required' => true,
            ),
        ),
    ),
    array(
        'key' => 'priceRange',
        'label' => 'Price Range',
        'type' => 'text',
        'placeholder' => '$$',
        'required' => false,
        'help' => 'e.g., $, $$, $$$, $$$$',
    ),
    array(
        'key' => 'openingHours',
        'label' => 'Opening Hours',
        'type' => 'repeater',
        'required' => false,
        'help' => 'Add your business hours',
        'fields' => array(
            array(
                'key' => 'dayOfWeek',
                'label' => 'Day',
                'type' => 'select',
                'options' => array(
                    'Monday' => 'Monday',
                    'Tuesday' => 'Tuesday',
                    'Wednesday' => 'Wednesday',
                    'Thursday' => 'Thursday',
                    'Friday' => 'Friday',
                    'Saturday' => 'Saturday',
                    'Sunday' => 'Sunday',
                ),
                'required' => true,
            ),
            array(
                'key' => 'opens',
                'label' => 'Opens',
                'type' => 'text',
                'placeholder' => '09:00',
                'required' => true,
            ),
            array(
                'key' => 'closes',
                'label' => 'Closes',
                'type' => 'text',
                'placeholder' => '17:00',
                'required' => true,
            ),
        ),
    ),
);
