<?php
return array(
    'name' => 'Restaurant',
    'description' => 'Restaurant schema markup for dining establishments',
    'fields' => array(
        array(
            'key' => 'name',
            'label' => 'Restaurant Name',
            'type' => 'text',
            'placeholder' => 'The Golden Fork',
            'required' => true,
            'help' => 'Name of the restaurant',
        ),
        array(
            'key' => 'description',
            'label' => 'Description',
            'type' => 'textarea',
            'placeholder' => 'Enter restaurant description',
            'required' => false,
            'help' => 'A description of the restaurant',
        ),
        array(
            'key' => 'servesCuisine',
            'label' => 'Cuisine Type',
            'type' => 'text',
            'placeholder' => 'Italian, Mediterranean',
            'required' => false,
            'help' => 'Types of cuisine served',
        ),
        array(
            'key' => 'address',
            'label' => 'Street Address',
            'type' => 'text',
            'placeholder' => '123 Main Street',
            'required' => true,
            'help' => 'Street address of the restaurant',
        ),
        array(
            'key' => 'city',
            'label' => 'City',
            'type' => 'text',
            'placeholder' => 'Bangalore',
            'required' => true,
            'help' => 'City where the restaurant is located',
        ),
        array(
            'key' => 'postalCode',
            'label' => 'Postal Code',
            'type' => 'text',
            'placeholder' => '560001',
            'required' => false,
            'help' => 'Postal code',
        ),
        array(
            'key' => 'telephone',
            'label' => 'Phone Number',
            'type' => 'text',
            'placeholder' => '+91-80-12345678',
            'required' => false,
            'help' => 'Contact phone number',
        ),
        array(
            'key' => 'priceRange',
            'label' => 'Price Range',
            'type' => 'text',
            'placeholder' => '$$',
            'required' => false,
            'help' => 'Price range (e.g., $, $$, $$$, $$$$)',
        ),
    ),
);
