<?php
return array(
    'name' => 'Software Application',
    'description' => 'Software application schema markup',
    'fields' => array(
        array(
            'key' => 'name',
            'label' => 'Application Name',
            'type' => 'text',
            'placeholder' => 'My Awesome App',
            'required' => true,
            'help' => 'Name of the software application',
        ),
        array(
            'key' => 'description',
            'label' => 'Description',
            'type' => 'textarea',
            'placeholder' => 'Enter software description',
            'required' => true,
            'help' => 'A description of the software',
        ),
        array(
            'key' => 'operatingSystem',
            'label' => 'Operating System',
            'type' => 'text',
            'placeholder' => 'Windows, macOS, Linux, iOS, Android',
            'required' => false,
            'help' => 'Supported operating systems',
        ),
        array(
            'key' => 'applicationCategory',
            'label' => 'Application Category',
            'type' => 'text',
            'placeholder' => 'BusinessApplication',
            'required' => false,
            'help' => 'Category of the application (e.g., BusinessApplication, GameApplication)',
        ),
        array(
            'key' => 'price',
            'label' => 'Price',
            'type' => 'text',
            'placeholder' => '0',
            'required' => false,
            'help' => 'Price of the software (use 0 for free)',
        ),
        array(
            'key' => 'currency',
            'label' => 'Currency',
            'type' => 'text',
            'placeholder' => 'USD',
            'required' => false,
            'help' => 'Currency code (USD, EUR, INR, etc.)',
        ),
        array(
            'key' => 'ratingValue',
            'label' => 'Rating Value',
            'type' => 'text',
            'placeholder' => '4.5',
            'required' => false,
            'help' => 'Average rating value (0-5)',
        ),
        array(
            'key' => 'ratingCount',
            'label' => 'Rating Count',
            'type' => 'text',
            'placeholder' => '100',
            'required' => false,
            'help' => 'Number of ratings',
        ),
    ),
);
